export const ALL_POST_REQUEST = 'ALL_POST_REQUEST'
export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_FAILED = 'ALL_POST_FAILED'

export const ONE_POST_REQUEST = 'ONE_POST_REQUEST'
export const ONE_POST_SUCCESS = 'ONE_POST_SUCCESS'
export const ONE_POST_FAILED = 'ONE_POST_FAILED'

export const ALL_COMMENTS_REQUEST = 'ALL_COMMENTS_REQUEST'
export const ALL_COMMENTS_SUCCESS = 'ALL_COMMENTS_SUCCESS'
export const ALL_COMMENTS_FAILED = 'ALL_COMMENTS_FAILED'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAILED = 'ALL_USERS_FAILED'
